version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "nw"
