name: nw-test-suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.3.2"
      - run: poetry install
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "19.4.0"
          cache: "npm"
      - run: npm ci
      - run: poetry run python3 -m unittest ./nw/**/*.py
