name: nw-test-suite
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        include:
          - { os: macos-12, shell: bash }
          - { os: ubuntu-22.04, shell: bash }
          - { os: windows-2022, shell: powershell }
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "21.1.0"
      - run: npm ci
      - run: npm run lint
      - run: npm start
