name: nw-test-suite
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        include:
          - { os: macos-12, shell: bash }
          - { os: ubuntu-22.04, shell: bash }
          # - { os: windows-2022, shell: powershell }
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "20.5.0"
          cache: "npm"
      - run: corepack enable
      - run: npm i
      - run: npm run ci:fmt
      - run: npm run ci:lnt
      - run: npm start
